/lidar_camera_calib:
    ros__parameters:
        # Data path. adjust them!
        image_file: "/home/mechax/zyb/lidar_camera_calibration_data/calibration_img.jpg"
        pcd_file: "/home/mechax/zyb/lidar_camera_calibration_data/calibration_pcd.pcd"
        result_file: "/home/mechax/zyb/ros2_livox_camera_calibration/src/lidar_camera_calib/result/extrinsic.txt"

        # Camera Parameters. Adjust them!
        camera_matrix: [3135.31292,    0.     ,  526.87116,
            0.     , 3151.06425,  695.83061,
            0.     ,    0.     ,    1.     ]
        dist_coeffs: [-0.019203, 0.252109, 0.016576, -0.012270, 0.000000]

        # Calibration Parameters.!
        calib_config_file: "/home/mechax/zyb/ros2_livox_camera_calibration/src/lidar_camera_calib/config/config_indoor.yaml"
        use_rough_calib: true # set true if your initial_extrinsic is bad
        save_img: true
        folder: "/home/mechax/zyb/ros2_livox_camera_calibration/src/lidar_camera_calib/result"