%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/image_raw"

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0,   -1.5,   0.0,    0.5,
         0.0,  0.0,  -1.0,    0.75,
         1.0,   0.0,    0.0,    -1.6,
         0.0,   0.0,    0.0,    1.0]

# [0.0,   -1.0,   0.0,    0.1,
#         0.0,  0.0,  -1.0,    0.0,
#         1.0,   0.0,    0.0,    0.16,
#         0.0,   0.0,    0.0,    1.0]
# Params for Canny Edge Extraction

Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 1.0
Voxel.down_sample_size: 0.02
Plane.min_points_size: 60
Plane.normal_theta_min: 45
Plane.normal_theta_max: 135
Plane.max_size: 8
Ransac.dis_threshold: 0.02
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06
